
name: Deployment On Dev Environment

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy To Dev Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check Node
        run: node -v
