
name: Deployment On Dev Environment

on:
  push:
    branches:
      - 'dev'

jobs:
  deploy:
    name: Deploy To Dev Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SSH To Dev Server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          
        run: |
          echo "$PRIVATE_KEY" > private_key 
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          ./.deployment.sh'
