# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy To EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build 
    - run: ls
    - run: ls ./build
    
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_SERVER }}
          REMOTE_USER: ${{ secrets.HOST_NAME }}
          
    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo apt-get -y update 
            mv ./build /home/ubuntu
